import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {
  Container,
  Button,
  Input,
  Spacer,
  Text,
  Link
} from '@nextui-org/react';
import NavBar from '../components/NavBar';
import Dashboard from '../components/Dashboard';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextUI | Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar/>
      <Container
        as="main"
        //display="flex"
        direction="column"
        //justify="center"
        alignItems="flex-start"
        style={{ height: '100vh' }}
      >
        <Spacer y={1}/>
        <Dashboard/>
      </Container>
    </div>
  );
}
